-- Sergio Rivera 2023
--
-- Pluggable Database creation
--

-- 1) Change IP and PORT!!
-- 2) If you are using Oracle XE, replace "FREE" by "XE"

-- conexión al esquema FREE, que contiene todo
-- con el usuario sys y roll sysdba

!clear

connect sys/debianOracle@localhost:1521/FREE as sysdba;

alter pluggable database mnist close;
-- alter pluggable database mnist unplug into '/tmp/mnist.pdb';
DROP pluggable database mnist including datafiles;

-- DROP user mnist;

-- creamos una base de datos pluggable
create pluggable database mnist ADMIN USER mnist IDENTIFIED by mnist
  FILE_NAME_CONVERT=(
    '/opt/oracle/oradata/FREE/pdbseed/system01.dbf', '/opt/oracle/oradata/FREE/NEW_PDB/system01.dbf',
    '/opt/oracle/oradata/FREE/pdbseed/sysaux01.dbf', '/opt/oracle/oradata/FREE/NEW_PDB/sysaux01.dbf',
    '/opt/oracle/oradata/FREE/pdbseed/undotbs01.dbf', '/opt/oracle/oradata/FREE/NEW_PDB/undotbs01.dbf',
    '/opt/oracle/oradata/FREE/pdbseed/temp01.dbf', '/opt/oracle/oradata/FREE/NEW_PDB/temp01.dbf'
  )
  STORAGE UNLIMITED TEMPFILE REUSE;

-- abrimos la base de datos
alter pluggable database mnist open;

-- cerrar base de datos
-- alter pluggable database mnist close;

-- eliminar base de datos
-- drop pluggable database  mnist;

show pdbs;

-- usamos la base de datos pluggable recién creada
alter session set container=mnist;

-- o nos conectamos a la plugable con usuario de sistema
connect sys/debianOracle@localhost:1521/mnist as sysdba;

-- QUOTAS
ALTER USER mnist QUOTA UNLIMITED ON "SYSTEM";
ALTER USER mnist QUOTA UNLIMITED ON "SYSAUX";

-- ROLES
GRANT "DV_MONITOR" TO mnist ;
GRANT "SHARDED_SCHEMA_OWNER" TO mnist ;
GRANT "WM_ADMIN_ROLE" TO mnist ;
GRANT "OLAP_USER" TO mnist ;
GRANT "DV_SECANALYST" TO mnist ;
GRANT "MAINTPLAN_APP" TO mnist ;
GRANT "RECOVERY_CATALOG_OWNER_VPD" TO mnist ;
GRANT "AVTUNE_PKG_ROLE" TO mnist ;
GRANT "GDS_CATALOG_SELECT" TO mnist ;
GRANT "PGX_SESSION_GET_PUBLISHED_GRAPH" TO mnist ;
GRANT "SCHEDULER_ADMIN" TO mnist ;
GRANT "PROVISIONER" TO mnist ;
GRANT "PGX_SERVER_GET_INFO" TO mnist ;
GRANT "APPLICATION_TRACE_VIEWER" TO mnist ;
GRANT "LBAC_DBA" TO mnist ;
GRANT "OSAK_ADMIN_ROLE" TO mnist ;
GRANT "DV_DATAPUMP_NETWORK_LINK" TO mnist ;
GRANT "GSMUSER_ROLE" TO mnist ;
GRANT "GATHER_SYSTEM_STATISTICS" TO mnist ;
GRANT "LOGSTDBY_ADMINISTRATOR" TO mnist ;
GRANT "DBJAVASCRIPT" TO mnist ;
GRANT "GSM_POOLADMIN_ROLE" TO mnist ;
GRANT "HS_ADMIN_ROLE" TO mnist ;
GRANT "OGG_APPLY" TO mnist ;
GRANT "XS_SESSION_ADMIN" TO mnist ;
GRANT "GSMCATUSER_ROLE" TO mnist ;
GRANT "JAVADEBUGPRIV" TO mnist ;
GRANT "CONNECT" TO mnist ;
GRANT "SQL_FIREWALL_ADMIN" TO mnist ;
GRANT "ACCHK_READ" TO mnist ;
GRANT "PGX_SESSION_READ_MODEL" TO mnist ;
GRANT "SQL_FIREWALL_VIEWER" TO mnist ;
GRANT "SODA_APP" TO mnist ;
GRANT "BDSQL_ADMIN" TO mnist ;
GRANT "PGX_SESSION_NEW_GRAPH" TO mnist ;
GRANT "GSMADMIN_ROLE" TO mnist ;
GRANT "GRAPH_DEVELOPER" TO mnist ;
GRANT "JAVAUSERPRIV" TO mnist ;
GRANT "XDB_SET_INVOKER" TO mnist ;
GRANT "JAVA_ADMIN" TO mnist ;
GRANT "DBFS_ROLE" TO mnist ;
GRANT "PDB_DBA" TO mnist ;
GRANT "RDFCTX_ADMIN" TO mnist ;
GRANT "CDB_DBA" TO mnist ;
GRANT "JAVASYSPRIV" TO mnist ;
GRANT "GSMROOTUSER_ROLE" TO mnist ;
GRANT "HS_ADMIN_SELECT_ROLE" TO mnist ;
GRANT "AUDIT_VIEWER" TO mnist ;
GRANT "RESOURCE" TO mnist ;
GRANT "DV_OWNER" TO mnist ;
GRANT "OGG_CAPTURE" TO mnist ;
GRANT "EXP_FULL_DATABASE" TO mnist ;
GRANT "OGG_APPLY_PROCREP" TO mnist ;
GRANT "PGX_SESSION_ADD_PUBLISHED_GRAPH" TO mnist ;
GRANT "CAPTURE_ADMIN" TO mnist ;
GRANT "OEM_ADVISOR" TO mnist ;
GRANT "OGG_SHARED_CAPTURE" TO mnist ;
GRANT "DBA" TO mnist ;
GRANT "PPLB_ROLE" TO mnist ;
GRANT "CTXAPP" TO mnist ;
GRANT "DV_AUDIT_CLEANUP" TO mnist ;
GRANT "OLAP_XS_ADMIN" TO mnist ;
GRANT "XS_CACHE_ADMIN" TO mnist ;
GRANT "GRAPH_USER" TO mnist ;
GRANT "DB_DEVELOPER_ROLE" TO mnist ;
GRANT "AUDIT_ADMIN" TO mnist ;
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO mnist ;
GRANT "AQ_ADMINISTRATOR_ROLE" TO mnist ;
GRANT "SYSUMF_ROLE" TO mnist ;
GRANT "DATAPUMP_CLOUD_IMP" TO mnist ;
GRANT "XDB_WEBSERVICES" TO mnist ;
GRANT "OPTIMIZER_PROCESSING_RATE" TO mnist ;
GRANT "RECOVERY_CATALOG_USER" TO mnist ;
GRANT "DV_ADMIN" TO mnist ;
GRANT "DV_POLICY_OWNER" TO mnist ;
GRANT "DV_GOLDENGATE_ADMIN" TO mnist ;
GRANT "IMP_FULL_DATABASE" TO mnist ;
GRANT "DV_XSTREAM_ADMIN" TO mnist ;
GRANT "DV_PATCH_ADMIN" TO mnist ;
GRANT "GGSYS_ROLE" TO mnist ;
GRANT "NOTIFICATIONS_USER" TO mnist ;
GRANT "XSTREAM_APPLY" TO mnist ;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO mnist ;
GRANT "EJBCLIENT" TO mnist ;
GRANT "HS_ADMIN_EXECUTE_ROLE" TO mnist ;
GRANT "JMXSERVER" TO mnist ;
GRANT "OLAP_DBA" TO mnist ;
GRANT "ADM_PARALLEL_EXECUTE_TASK" TO mnist ;
GRANT "JAVAIDPRIV" TO mnist ;
GRANT "SELECT_CATALOG_ROLE" TO mnist ;
GRANT "DGPDB_ROLE" TO mnist ;
GRANT "PGX_SESSION_MODIFY_MODEL" TO mnist ;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO mnist ;
GRANT "OEM_MONITOR" TO mnist ;
GRANT "PGX_SERVER_MANAGE" TO mnist ;
GRANT "GRAPH_ADMINISTRATOR" TO mnist ;
GRANT "AQ_USER_ROLE" TO mnist ;
GRANT "RECOVERY_CATALOG_OWNER" TO mnist ;
GRANT "DATAPUMP_CLOUD_EXP" TO mnist ;
GRANT "DV_GOLDENGATE_REDO_ACCESS" TO mnist ;
GRANT "XSTREAM_CAPTURE" TO mnist ;
GRANT "SAGA_CONNECT_ROLE" TO mnist ;
GRANT "SAGA_PARTICIPANT_ROLE" TO mnist ;
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO mnist ;
GRANT "EXECUTE_CATALOG_ROLE" TO mnist ;
GRANT "DV_ACCTMGR" TO mnist ;
GRANT "NOTIFICATIONS_ADMIN" TO mnist ;
GRANT "SAGA_ADM_ROLE" TO mnist ;
GRANT "PGX_SESSION_CREATE" TO mnist ;
GRANT "DBMS_MDX_INTERNAL" TO mnist ;
GRANT "DV_STREAMS_ADMIN" TO mnist ;
GRANT "XS_NAMESPACE_ADMIN" TO mnist ;
GRANT "BDSQL_USER" TO mnist ;
GRANT "AUTHENTICATEDUSER" TO mnist ;
GRANT "XS_CONNECT" TO mnist ;
GRANT "XDBADMIN" TO mnist ;
GRANT "PGX_SESSION_COMPILE_ALGORITHM" TO mnist ;

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO mnist ;
GRANT DROP ANY CONTEXT TO mnist ;
GRANT UPDATE ANY CUBE TO mnist ;
GRANT ALTER ANY ANALYTIC VIEW TO mnist ;
GRANT DROP ANY TRIGGER TO mnist ;
GRANT DROP ANY SQL TRANSLATION PROFILE TO mnist ;
GRANT ALTER PUBLIC DATABASE LINK TO mnist ;
GRANT CREATE ANY DOMAIN TO mnist ;
GRANT ALTER ANY INDEX TO mnist ;
GRANT DROP ANY SEQUENCE TO mnist ;
GRANT GRANT ANY SCHEMA PRIVILEGE TO mnist ;
GRANT ALTER PROFILE TO mnist ;
GRANT INHERIT ANY PRIVILEGES TO mnist ;
GRANT UNDER ANY TABLE TO mnist ;
GRANT KEEP SYSGUID TO mnist ;
GRANT CREATE ASSEMBLY TO mnist ;
GRANT CREATE ANY MLE TO mnist ;
GRANT DROP ANY LIBRARY TO mnist ;
GRANT ALTER ANY EDITION TO mnist ;
GRANT CREATE ROLE TO mnist ;
GRANT CREATE LIBRARY TO mnist ;
GRANT DROP ROLLBACK SEGMENT TO mnist ;
GRANT CREATE TRIGGER TO mnist ;
GRANT ALTER ANY PROCEDURE TO mnist ;
GRANT ADMINISTER DATABASE TRIGGER TO mnist ;
GRANT DROP ANY MEASURE FOLDER TO mnist ;
GRANT ADMINISTER SQL FIREWALL TO mnist ;
GRANT CREATE ANY PROCEDURE TO mnist ;
GRANT ALTER ANY OUTLINE TO mnist ;
GRANT CREATE ANY ANALYTIC VIEW TO mnist ;
GRANT EXECUTE ANY INDEXTYPE TO mnist ;
GRANT USE ANY JOB RESOURCE TO mnist ;
GRANT CREATE ANY DIRECTORY TO mnist ;
GRANT ALTER ANY RULE SET TO mnist ;
GRANT USE ANY SQL TRANSLATION PROFILE TO mnist ;
GRANT ALTER ANY MINING MODEL TO mnist ;
GRANT DEBUG CONNECT SESSION TO mnist ;
GRANT LOGMINING TO mnist ;
GRANT DROP ANY ATTRIBUTE DIMENSION TO mnist ;
GRANT CREATE ANY MINING MODEL TO mnist ;
GRANT CREATE LOCKDOWN PROFILE TO mnist ;
GRANT ALTER SESSION TO mnist ;
GRANT ALTER ANY PROPERTY GRAPH TO mnist ;
GRANT CREATE MATERIALIZED VIEW TO mnist ;
GRANT CREATE PLUGGABLE DATABASE TO mnist ;
GRANT DROP ANY ANALYTIC VIEW TO mnist ;
GRANT WRITE ANY ANALYTIC VIEW CACHE TO mnist ;
GRANT MERGE ANY VIEW TO mnist ;
GRANT CREATE ANY INDEX TO mnist ;
GRANT READ ANY ANALYTIC VIEW CACHE TO mnist ;
GRANT CREATE DIMENSION TO mnist ;
GRANT EXECUTE ANY RULE SET TO mnist ;
GRANT CREATE SQL TRANSLATION PROFILE TO mnist ;
GRANT ALTER ANY MATERIALIZED VIEW TO mnist ;
GRANT AUDIT SYSTEM TO mnist ;
GRANT CREATE OPERATOR TO mnist ;
GRANT MANAGE ANY QUEUE TO mnist ;
GRANT ALTER ANY SQL PROFILE TO mnist ;
GRANT GRANT ANY OBJECT PRIVILEGE TO mnist ;
GRANT CREATE INDEXTYPE TO mnist ;
GRANT AUDIT ANY TO mnist ;
GRANT INHERIT ANY REMOTE PRIVILEGES TO mnist ;
GRANT SYSKM TO mnist ;
GRANT DEBUG ANY PROCEDURE TO mnist ;
GRANT CREATE ANY MEASURE FOLDER TO mnist ;
GRANT CREATE ANY SEQUENCE TO mnist ;
GRANT CREATE MEASURE FOLDER TO mnist ;
GRANT UPDATE ANY CUBE BUILD PROCESS TO mnist ;
GRANT CREATE VIEW TO mnist ;
GRANT ALTER DATABASE LINK TO mnist ;
GRANT ALTER ANY ASSEMBLY TO mnist ;
GRANT ALTER ANY SQL TRANSLATION PROFILE TO mnist ;
GRANT CREATE ANY EVALUATION CONTEXT TO mnist ;
GRANT SELECT ANY MINING MODEL TO mnist ;
GRANT CREATE DOMAIN TO mnist ;
GRANT DELETE ANY CUBE DIMENSION TO mnist ;
GRANT ALTER ANY TABLE TO mnist ;
GRANT ALTER ANY ATTRIBUTE DIMENSION TO mnist ;
GRANT CREATE SESSION TO mnist ;
GRANT CREATE RULE TO mnist ;
GRANT BECOME USER TO mnist ;
GRANT SELECT ANY CUBE BUILD PROCESS TO mnist ;
GRANT SELECT ANY TABLE TO mnist ;
GRANT INSERT ANY MEASURE FOLDER TO mnist ;
GRANT DROP ANY DOMAIN TO mnist ;
GRANT CREATE ANY SQL PROFILE TO mnist ;
GRANT FORCE ANY TRANSACTION TO mnist ;
GRANT DELETE ANY TABLE TO mnist ;
GRANT ALTER ANY SEQUENCE TO mnist ;
GRANT SELECT ANY CUBE DIMENSION TO mnist ;
GRANT CREATE ANY EDITION TO mnist ;
GRANT CREATE EXTERNAL JOB TO mnist ;
GRANT CREATE TRUE CACHE TO mnist ;
GRANT DROP ANY MATERIALIZED VIEW TO mnist ;
GRANT CREATE ANY CUBE BUILD PROCESS TO mnist ;
GRANT FLASHBACK ANY TABLE TO mnist ;
GRANT DROP ANY RULE SET TO mnist ;
GRANT BACKUP ANY TABLE TO mnist ;
GRANT ALTER ANY CUBE TO mnist ;
GRANT CREATE CREDENTIAL TO mnist ;
GRANT CREATE TABLE TO mnist ;
GRANT EXECUTE ANY LIBRARY TO mnist ;
GRANT ADMINISTER REDACTION POLICY TO mnist ;
GRANT DROP ANY OUTLINE TO mnist ;
GRANT EXECUTE ASSEMBLY TO mnist ;
GRANT CREATE ANY HIERARCHY TO mnist ;
GRANT CREATE ANALYTIC VIEW TO mnist ;
GRANT CREATE ANY DIMENSION TO mnist ;
GRANT DROP ANY TABLE TO mnist ;
GRANT ALTER ANY DOMAIN TO mnist ;
GRANT ADMINISTER KEY MANAGEMENT TO mnist ;
GRANT ALTER ANY CLUSTER TO mnist ;
GRANT EXECUTE ANY CLASS TO mnist ;
GRANT ALTER ANY CUBE BUILD PROCESS TO mnist ;
GRANT CREATE ANY CREDENTIAL TO mnist ;
GRANT DROP ANY DIMENSION TO mnist ;
GRANT SYSBACKUP TO mnist ;
GRANT CREATE ANY RULE SET TO mnist ;
GRANT SELECT ANY SEQUENCE TO mnist ;
GRANT UNDER ANY TYPE TO mnist ;
GRANT MANAGE TABLESPACE TO mnist ;
GRANT DROP ANY OPERATOR TO mnist ;
GRANT CREATE ANY OPERATOR TO mnist ;
GRANT DROP ANY HIERARCHY TO mnist ;
GRANT EXECUTE ANY DOMAIN TO mnist ;
GRANT CREATE PROPERTY GRAPH TO mnist ;
GRANT EXEMPT IDENTITY POLICY TO mnist ;
GRANT CREATE TYPE TO mnist ;
GRANT CREATE TABLESPACE TO mnist ;
GRANT SELECT ANY TRANSACTION TO mnist ;
GRANT TABLE RETENTION TO mnist ;
GRANT DELETE ANY MEASURE FOLDER TO mnist ;
GRANT CREATE ANY CUBE TO mnist ;
GRANT LOCK ANY TABLE TO mnist ;
GRANT CREATE EVALUATION CONTEXT TO mnist ;
GRANT DROP ANY TYPE TO mnist ;
GRANT CREATE ANY PROPERTY GRAPH TO mnist ;
GRANT ADVISOR TO mnist ;
GRANT CREATE PUBLIC DATABASE LINK TO mnist ;
GRANT ANALYZE ANY TO mnist ;
GRANT CREATE ATTRIBUTE DIMENSION TO mnist ;
GRANT DROP ANY RULE TO mnist ;
GRANT INSERT ANY CUBE DIMENSION TO mnist ;
GRANT CREATE ROLLBACK SEGMENT TO mnist ;
GRANT CREATE ANY JOB TO mnist ;
GRANT ALTER USER TO mnist ;
GRANT QUERY REWRITE TO mnist ;
GRANT SELECT ANY DICTIONARY TO mnist ;
GRANT CREATE PUBLIC SYNONYM TO mnist ;
GRANT DROP LOGICAL PARTITION TRACKING TO mnist ;
GRANT GLOBAL QUERY REWRITE TO mnist ;
GRANT ALTER ANY CUBE DIMENSION TO mnist ;
GRANT CREATE ANY CUBE DIMENSION TO mnist ;
GRANT DROP ANY CLUSTER TO mnist ;
GRANT CREATE ANY RULE TO mnist ;
GRANT UPDATE ANY CUBE DIMENSION TO mnist ;
GRANT SYSDBA TO mnist ;
GRANT CREATE LOGICAL PARTITION TRACKING TO mnist ;
GRANT READ ANY PROPERTY GRAPH TO mnist ;
GRANT CREATE MLE TO mnist ;
GRANT ADMINISTER RESOURCE MANAGER TO mnist ;
GRANT CREATE ANY SYNONYM TO mnist ;
GRANT DROP ANY SYNONYM TO mnist ;
GRANT DROP ANY MINING MODEL TO mnist ;
GRANT EXECUTE ANY PROCEDURE TO mnist ;
GRANT DROP ANY MLE TO mnist ;
GRANT CREATE SYNONYM TO mnist ;
GRANT DROP ANY PROPERTY GRAPH TO mnist ;
GRANT SET CONTAINER TO mnist ;
GRANT EXECUTE ANY PROGRAM TO mnist ;
GRANT EXEMPT REDACTION POLICY TO mnist ;
GRANT EXECUTE ANY TYPE TO mnist ;
GRANT ON COMMIT REFRESH TO mnist ;
GRANT DEBUG CONNECT ANY TO mnist ;
GRANT CREATE SEQUENCE TO mnist ;
GRANT ADMINISTER ROW LEVEL SECURITY POLICY TO mnist ;
GRANT CREATE HIERARCHY TO mnist ;
GRANT SELECT ANY MEASURE FOLDER TO mnist ;
GRANT COMMENT ANY MINING MODEL TO mnist ;
GRANT ADMINISTER SQL TUNING SET TO mnist ;
GRANT ADMINISTER FINE GRAINED AUDIT POLICY TO mnist ;
GRANT SYSOPER TO mnist ;
GRANT CREATE ANY INDEXTYPE TO mnist ;
GRANT KEEP DATE TIME TO mnist ;
GRANT DROP ANY INDEX TO mnist ;
GRANT RESTRICTED SESSION TO mnist ;
GRANT SYSDG TO mnist ;
GRANT DEQUEUE ANY QUEUE TO mnist ;
GRANT ENABLE DIAGNOSTICS TO mnist ;
GRANT ANALYZE ANY DICTIONARY TO mnist ;
GRANT ALTER ANY INDEXTYPE TO mnist ;
GRANT TRANSLATE ANY SQL TO mnist ;
GRANT ADMINISTER ANY SQL TUNING SET TO mnist ;
GRANT CREATE USER TO mnist ;
GRANT EXECUTE ANY OPERATOR TO mnist ;
GRANT CREATE CUBE BUILD PROCESS TO mnist ;
GRANT CREATE PROFILE TO mnist ;
GRANT ALTER ANY MLE TO mnist ;
GRANT ALTER ANY ROLE TO mnist ;
GRANT UPDATE ANY TABLE TO mnist ;
GRANT ALTER ANY LIBRARY TO mnist ;
GRANT DROP ANY VIEW TO mnist ;
GRANT CREATE ANY CLUSTER TO mnist ;
GRANT EXECUTE ANY RULE TO mnist ;
GRANT ALTER TABLESPACE TO mnist ;
GRANT UNDER ANY VIEW TO mnist ;
GRANT EXECUTE ANY ASSEMBLY TO mnist ;
GRANT GRANT ANY PRIVILEGE TO mnist ;
GRANT ALTER ANY TRIGGER TO mnist ;
GRANT CREATE ANY VIEW TO mnist ;
GRANT ALTER LOCKDOWN PROFILE TO mnist ;
GRANT EXPORT FULL DATABASE TO mnist ;
GRANT ALTER ANY MEASURE FOLDER TO mnist ;
GRANT ALTER ANY EVALUATION CONTEXT TO mnist ;
GRANT TEXT DATASTORE ACCESS TO mnist ;
GRANT FLASHBACK ARCHIVE ADMINISTER TO mnist ;
GRANT IMPORT FULL DATABASE TO mnist ;
GRANT CREATE ANY OUTLINE TO mnist ;
GRANT COMMENT ANY TABLE TO mnist ;
GRANT READ ANY TABLE TO mnist ;
GRANT CREATE DATABASE LINK TO mnist ;
GRANT DROP PUBLIC SYNONYM TO mnist ;
GRANT DROP USER TO mnist ;
GRANT CHANGE NOTIFICATION TO mnist ;
GRANT CREATE MINING MODEL TO mnist ;
GRANT INSERT ANY TABLE TO mnist ;
GRANT DROP LOCKDOWN PROFILE TO mnist ;
GRANT DROP PROFILE TO mnist ;
GRANT CREATE ANY MATERIALIZED VIEW TO mnist ;
GRANT CREATE RULE SET TO mnist ;
GRANT EXEMPT ACCESS POLICY TO mnist ;
GRANT MANAGE SCHEDULER TO mnist ;
GRANT FORCE TRANSACTION TO mnist ;
GRANT DROP ANY CUBE BUILD PROCESS TO mnist ;
GRANT ALTER ANY TYPE TO mnist ;
GRANT DROP ANY PROCEDURE TO mnist ;
GRANT CREATE ANY SQL TRANSLATION PROFILE TO mnist ;
GRANT DROP PUBLIC DATABASE LINK TO mnist ;
GRANT DROP ANY INDEXTYPE TO mnist ;
GRANT DROP ANY SQL PROFILE TO mnist ;
GRANT EXECUTE DYNAMIC MLE TO mnist ;
GRANT ALTER SYSTEM TO mnist ;
GRANT UNLIMITED TABLESPACE TO mnist ;
GRANT DROP ANY ROLE TO mnist ;
GRANT ALTER ANY DIMENSION TO mnist ;
GRANT DROP ANY CUBE DIMENSION TO mnist ;
GRANT DROP ANY CUBE TO mnist ;
GRANT CREATE ANY TRIGGER TO mnist ;
GRANT DROP ANY ASSEMBLY TO mnist ;
GRANT CREATE ANY TABLE TO mnist ;
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO mnist ;
GRANT DROP ANY DIRECTORY TO mnist ;
GRANT ENQUEUE ANY QUEUE TO mnist ;
GRANT DROP ANY EVALUATION CONTEXT TO mnist ;
GRANT CREATE ANY ASSEMBLY TO mnist ;
GRANT CREATE ANY TYPE TO mnist ;
GRANT REDEFINE ANY TABLE TO mnist ;
GRANT CREATE CLUSTER TO mnist ;
GRANT CREATE ANY CONTEXT TO mnist ;
GRANT EXECUTE ANY EVALUATION CONTEXT TO mnist ;
GRANT RESUMABLE TO mnist ;
GRANT CREATE ANY LIBRARY TO mnist ;
GRANT DROP ANY EDITION TO mnist ;
GRANT CREATE PROCEDURE TO mnist ;
GRANT ALTER DATABASE TO mnist ;
GRANT SELECT ANY CUBE TO mnist ;
GRANT GRANT ANY ROLE TO mnist ;
GRANT ALTER ANY RULE TO mnist ;
GRANT CREATE ANY ATTRIBUTE DIMENSION TO mnist ;
GRANT CREATE CUBE DIMENSION TO mnist ;
GRANT ALTER ANY OPERATOR TO mnist ;
GRANT CREATE CUBE TO mnist ;
GRANT ALTER RESOURCE COST TO mnist ;
GRANT ALTER ANY HIERARCHY TO mnist ;
GRANT DROP TABLESPACE TO mnist ;
GRANT ALTER ROLLBACK SEGMENT TO mnist ;
GRANT PURGE DBA_RECYCLEBIN TO mnist ;

-- conexión a la plugable con el nuevo usuario
connect mnist/mnist@localhost:1521/mnist;

-- DATABASE CREATION:
@mnist

